package bss;

import ij.IJ;
import ij.ImagePlus;
import ij.plugin.PlugIn;

public class RestoreCFGMapping implements PlugIn
{

	@Override
	public void run( String arg )
	{
		ImagePlus imp = IJ.getImage();		
		if (imp == null)
		{
		    IJ.noImage();
		    return;
		}		
		CFGParameters cfgParams = new CFGParameters();
		if(!cfgParams.loadFromImagePlus( imp ))
		{
			//IJ.error( "This is not a cytofluorogram generated by LogColocalization plugin!" );
			return;
		}
		
		CFGParameters.applyHistParameters(imp, cfgParams);
		IJ.log( "BigScopeScatter v." + GlobalParameters.sVersion + ". Loaded image cytofluorogram parameters." );
		cfgParams.printParams();
	}
}
